version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: |
          pip install .
          pip install .[tests]
          python3 towerverseserver/server.py --local --test &
          pytest towerverseserver/tests
          kill $!
